trigger:
  branches:
    include:
      - main

pool:
  name: 'secureops-local-agent'

variables:
  - group: secureops-keyvault-secrets
  - name: imageRepository
    value: 'secureops-app'
  - name: containerRegistry
    value: 'secureopssadia.azurecr.io'
  - name: dockerfilePath
    value: 'docker/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildPush
    steps:
    - task: Docker@2
      displayName: 'Build and Push to ACR'
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: 'secureops-acr-conn'
        tags: |
          $(tag)

- stage: Deploy
  displayName: 'Deploy to Production'
  dependsOn: Build
  jobs:
  - deployment: DeployToACI
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deployed $(tag) successfully!"
            displayName: 'Deployment Complete'
